prometheus:
    host: localhost
    port: 8000
    interval: 20
    exporters:
        - alerts_exporter
        - memory_exporter
        - pcie_exporter
        - power_exporter
        - storage_exporter
        - thermal_exporter
        - gpu_exporter
nvsm:
    host: localhost
    port: 273
